config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("member/", include("members.urls", namespace="members")),
    path("contact/", include("contacts.urls",namespace="contacts")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from contacts import views as contact_views

app_name = "contacts"

urlpatterns = [
    path("send/", contact_views.renderContact, name="send")
]

core/urls.py
from django.urls import path
from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.renderHome, name="home"),
]

members/urls.py
from django.urls import path
from members import views as member_views

app_name = "members"

urlpatterns = [
    path("list", member_views.member_list_view_handler, name="member_list"),
]

contacts/models.py
from django.db import models

class contactFileModel(models.Model) :
    file = models.ImageField(null=True, default=True)
    contact = models.ForeignKey(
        "ContactModel", related_name="contact", on_delete=models.CASCADE
    )

class ContactModel(models.Model) :

    name = models.CharField(max_length=80)
    loc = models.CharField(max_length=30)
    email = models.EmailField()
    mobile = models.CharField(max_length=20)
    contents = models.TextField()

    created = models.DateField(auto_now_add=True)

  

    def __str__(self):
        return f"{self.name}-{self.created}"

    class Meta :
        verbose_name_plural = "CONTACTS"

core/models.py
from django.db import models

# Create your models here.

doc_boards/models.py
from django.db import models
from django.contrib.auth.models import User


class FileModel(models.Model):

    caption = models.CharField(max_length=100)
    file = models.FileField()
    board = models.ForeignKey("DocBoardModel", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name_plural = "Files"


class DocBoardModel(models.Model):

    CHOICE_HTML = "html"
    CHOICE_CSS = "css"
    CHOICE_JS = "javascript"
    CHOICE_ES6 = "es6"
    CHOICE_NODE = "node.js"
    CHOICE_JAVA = "java"
    CHOICE_PYTHON = "python"
    CHOICE_SQL = "sql"
    CHOICE_REACT = "react"
    CHOICE_RN = "react-native"
    CHOICE_FIREBASE = "firebase"
    CHOICE_GRAPHQL = "graphql"

    CHOICES_TYPE = (
        (CHOICE_HTML, "HTML"),
        (CHOICE_CSS, "CSS"),
        (CHOICE_JS, "JS"),
        (CHOICE_ES6, "ES6"),
        (CHOICE_NODE, "NODE"),
        (CHOICE_JAVA, "JAVA"),
        (CHOICE_PYTHON, "PYTHON"),
        (CHOICE_SQL, "SQL"),
        (CHOICE_REACT, "REACT"),
        (CHOICE_RN, "RN"),
        (CHOICE_FIREBASE, "FIREBASE"),
        (CHOICE_GRAPHQL, "GRAPHQL"),
    )

    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, related_name="doc_board", on_delete=models.CASCADE)
    description = models.TextField()
    board_type = models.CharField(choices=CHOICES_TYPE, max_length=40)
    like_count = models.IntegerField(default=0)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def displayUser(self):
        return self.author.username

    displayUser.short_description = "author"

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "DOC_BOARDS"

members/models.py
from django.db import models


class SkillModel(models.Model):
    """ Skill Model Definition """

    skill_name = models.CharField(max_length=40)

    def __str__(self):
        return self.skill_name

    class Meta:
        verbose_name_plural = "SKILLS"


class MemberModel(models.Model):
    """ Member Model Definition """

    GENDER_MALE = "Male"
    GENDER_FEMALE = "Female"
    GENDER_OTHER = "Other"

    GENDER_CHOICES = (
        (GENDER_MALE, "male"),
        (GENDER_FEMALE, "female"),
        (GENDER_OTHER, "other"),
    )

    name = models.CharField(max_length=30)
    birth = models.DateField()
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10)
    avatar = models.ImageField()
    mobile = models.CharField(max_length=12)
    email = models.EmailField(max_length=50)
    description = models.TextField(blank=True)
    skills = models.ManyToManyField("SkillModel", blank=True)

    def __str__(self):
        return self.name

    def view_mobile(self):

        current_value = self.mobile
        max_len = len(current_value)

        first_mobile = current_value[0:3]
        second_mobile = current_value[3:7]
        third_mobile = current_value[7:max_len]

        return f"{first_mobile}-{second_mobile}-{third_mobile}"

    view_mobile.short_description = "MOBILE"

    def count_skills(self):
        return f"{self.skills.all().count()}개"

    count_skills.short_description = "SKILLS"

    class Meta:
        verbose_name_plural = "MEMBERS"

portpolios/models.py
from django.db import models


class PortPolioModel(models.Model):

    thumbnail = models.ImageField()
    title = models.CharField(max_length=80)
    sub_title = models.CharField(max_length=100)
    contents = models.TextField()
    url = models.CharField(max_length=100)
    participants = models.ManyToManyField("members.MemberModel", blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "PORTPOLIOS"

contacts/views.py
from django.shortcuts import render

def renderContact(request):
    
    return render(request, "screens/contact.html")

core/views.py
from django.shortcuts import render


def renderHome(request):

    return render(
        request,
        "screens/home.html",
    )

doc_boards/views.py
from django.shortcuts import render
from . import models as member_models


def member_list_view_handler(request):

    members = member_models.MemberModel.objects.all()

    for mem in members:
        if mem.pk % 2 == 0:
            mem.isEven = True
        else:
            mem.isEven = False

    
    

    return render(request, "screens/member_list.html", context={"members": members})

members/views.py
from django.shortcuts import render
from . import models as member_models


def member_list_view_handler(request):

    members = member_models.MemberModel.objects.all()

    for mem in members:
        if mem.pk % 2 == 0:
            mem.isEven = True
        else:
            mem.isEven = False
    return render(request, "screens/member_list.html", context={"members": members})

portpolios/views.py
from django.shortcuts import render

# Create your views here.

theme_team/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block page_title %} {% endblock page_title %} | TEAM</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% load tailwind_tags %}{% load fontawesome_5 %}
  </head>

  <body class="bg-gray-900 font-serif leading-normal tracking-normal">
    <!--  -->
    {% include './header.html' %}

    <!--  -->
    {% block content %}
    <!--  -->
    {% tailwind_css %} {% fontawesome_5_static %}

    <!--  -->
    {% endblock content %}
  </body>
</html>

theme_team/templates/header.html
<div class="header-2">
  <nav class="bg-white py-2 md:py-4">
    <div class="container px-4 mx-auto md:flex md:items-center">
      <div class="flex justify-between items-center">
        <a href="/" class="font-bold text-xl text-indigo-600">FWR</a>
        <button
          class="
            border border-solid border-gray-600
            px-3
            py-1
            rounded
            text-gray-600
            opacity-50
            hover:opacity-75
            md:hidden
          "
          id="navbar-toggle"
        >
          <i class="fas fa-bars"></i>
        </button>
      </div>

      <div
        class="hidden md:flex flex-col md:flex-row md:ml-auto mt-3 md:mt-0"
        id="navbar-collapse"
      >
       
        <a
          href="/member/list"
          id="header-member-js"
          class="
            p-2
            lg:px-4
            md:mx-2
            text-gray-600
            rounded
            hover:bg-gray-200
            hover:text-gray-700
            transition-colors
            duration-300
          "
          >Member</a
        >
        <a
          href="#"
          id="header-features-js"
          class="
            p-2
            lg:px-4
            md:mx-2
            text-gray-600
            rounded
            hover:bg-gray-200
            hover:text-gray-700
            transition-colors
            duration-300
          "
          >Features</a
        >
        <a
          href="#"
          id="header-pricing-js"
          class="
            p-2
            lg:px-4
            md:mx-2
            text-gray-600
            rounded
            hover:bg-gray-200
            hover:text-gray-700
            transition-colors
            duration-300
          "
          >Pricing</a
        >
        <a
          href="{% url "contacts:send" %}" 
          id="header-contact-js"
          class="
            p-2
            lg:px-4
            md:mx-2
            text-gray-600
            rounded
            hover:bg-gray-200
            hover:text-gray-700
            transition-colors
            duration-300
          "
          >Contact</a
        >
      </div>
    </div>
  </nav>
</div>

<script>
  let toggleBtn = document.querySelector("#navbar-toggle");
  let collapse = document.querySelector("#navbar-collapse");

  toggleBtn.onclick = () => {
    collapse.classList.toggle("hidden");
    collapse.classList.toggle("flex");
  };


  
  const url = window.location.href;
  const urls =  url.split("/");


  const allMenu = [
                    "", // Home
                    "member", //memeber/list
                    "contact", //contact/send
                  ];


  


  // 화면이 로드 된 후! 
  // selectDOM이 있을 때!

  window.onload = () => {
    allMenu.forEach(name => {
      const selectDOM = document.getElementById(`header-${name}-js`);
      
      if(selectDOM) {
        if(name === urls[3]) {
          selectDOM.classList.remove("text-gray-600");
          selectDOM.classList.remove("hover:bg-gray-200");
          selectDOM.classList.remove("hover:text-gray-700");
          selectDOM.classList.remove("transition-colors");
          selectDOM.classList.remove("duration-300");
          selectDOM.classList.add("text-white");
          selectDOM.classList.add("bg-indigo-600");
          
        } else {
          selectDOM.classList.add("text-gray-600");
          selectDOM.classList.add("hover:bg-gray-200");
          selectDOM.classList.add("hover:text-gray-700");
          selectDOM.classList.add("transition-colors");
          selectDOM.classList.add("duration-300");
          selectDOM.classList.remove("text-white");
          selectDOM.classList.remove("bg-indigo-600");
        }
      }
      
    })
  }

 






  

  

</script>

theme_team/templates/screens/contact.html
{% extends '../base.html' %}


{% block page_title %}
    CONTACT
{% endblock page_title %}


{% block content %}{% load tailwind_tags %}{% tailwind_css %}

<h1>Hello contactPAGE</h1>

{% endblock content %}

theme_team/templates/screens/home.html
{% extends '../base.html' %}
<!--  -->
{% block page_title %} HOME {% endblock page_title%}

<!--  -->
{% block content %} {% load tailwind_tags %} {% tailwind_css %}

<section class="w-full flex flex-col items-center justify-center mt-10">
  <div class="bg-white w-3/4 h-auto shadow-lg mb-20">
    <img
      src="https://d3lkc3n5th01x7.cloudfront.net/wp-content/uploads/2020/09/29020725/hire-stellar-developer.jpg"
    />
  </div>

  <div class="text-white mb-20 flex flex-col items-center justify-center">
    <p class="text-2xl">Team Of Special And Professional Developers</p>
    <div class="w-96 h-1 rounded-xl bg-gray-600 mt-8"></div>
    <p class="text-5xl mt-6">D.D Coders</p>
  </div>
</section>

<section
  class="w-full mb-20 flex flex-row items-center justify-around relative"
>
  <p class="absolute text-gray-300 text-7xl top-3 left-20 text-opacity-30">
    D E V E L O P E R
  </p>
  <p class="absolute text-gray-300 text-5xl bottom-3 right-20 text-opacity-30">
    C O D E
  </p>

  <div class="w-2/5 h-auto">
    <img
      class="object-cover"
      src="https://specials-images.forbesimg.com/imageserve/605e463506a5b6d6b54383bb/960x0.jpg?cropX1=0&cropX2=630&cropY1=0&cropY2=473"
    />
  </div>
  <div class="w-2/5 h-auto">
    <img
      class="object-cover"
      src="https://specials-images.forbesimg.com/imageserve/605e463506a5b6d6b54383bb/960x0.jpg?cropX1=0&cropX2=630&cropY1=0&cropY2=473"
    />
  </div>
</section>

<section class="mt-60 w-full flex flex-col items-center justify-center mb-40">
  <div class="w-3/5 h-96 bg-black bg-opacity-30 text-white p-24 relative">
    <div
      class="
        absolute
        w-56
        h-96
        bg-indigo-500 bg-opacity-20
        -bottom-20
        -right-20
        p-6
        flex flex-col
        items-center
        justify-around
      "
    >
      <p class="text-xl">W E B</p>
      <p class="text-xl">M O B I L E</p>
      <p class="text-xl">S Y S T E M</p>
      <p class="text-xl">A I</p>
      <p class="text-xl">P L A T F O R M</p>
    </div>

    <h2 class="text-5xl mb-20">🍀 DUMMY TITLE</h2>

    <ul class="text-xl list-decimal pl-12">
      <li>Dummy TextData Bla Bla....</li>
      <li>Dummy TextData Bla Bla Bla Bla....</li>
      <li>Dummy TextData Bla Bla Bla Bla Bla....</li>
      <li>Dummy TextData Bla Bla Bla Bla....</li>
    </ul>
  </div>
</section>

{% endblock content %}